# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='canSeeImages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='canSeePosts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], max_length=32),
        ),
    ]
