# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20170407_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
