# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20170325_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://127.0.0.1:8000'),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://127.0.0.1:8000'),
        ),
    ]
