# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20170325_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='url',
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
