# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20170325_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
        migrations.AddField(
            model_name='post',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/'),
            preserve_default=False,
        ),
    ]
