# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20170325_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='host',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://127.0.0.1:8000/'),
            preserve_default=False,
        ),
    ]
